string = input('Gimme some text: ' )
string = string.lower()
print('Number of "a" :', string.count('a'))
print('Number of "e" :', string.count('e'))
print('Number of "y" :', string.count('y'))
print('Number of "u" :', string.count('u'))
print('Number of "i" :', string.count('i'))
print('Number of "o" :', string.count('o'))