# Generated by Django 4.2.3 on 2023-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='author',
            name='new_field',
            field=models.CharField(default='test value', max_length=100),
            preserve_default=False,
        ),
    ]
