# Generated by Django 4.2.3 on 2023-09-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_author_author_name_author_new_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='new_field',
        ),
    ]
